### ISSUE TITLE
The performance

### ISSUE THREAD

**Issue by he010103** [foolwood/DCFNet_pytorch#1]
@foolwood  Hi, Do the DCFNet_pytorch have the same performance as the DCFNet_matlab?

**Comment by foolwood** [comment]
The AUC on OTB2013 decreases 1.4% (65.1%) compared to the [MatConvnet implementation](https://github.com/foolwood/DCFNet).
You can tune the hyper-parameter to recover the performance via https://github.com/foolwood/DCFNet_pytorch.

Due to the shortage of GPU, I do not tune it myself. 

I will update a better parameter after VOT2018 challenge.

**Comment by he010103** [comment]
I test the DCFNet today. The result:
OTB2013 Best: result/OTB2013/DCFNet_test(0.6478), a little different
I use python2.7 and pytorch 0.4

**Comment by foolwood** [comment]
@he010103 
param.pth_scale_step_1.030_scale_penalty_0.990_interp_factor_0.012

You can try this param. It achieves an AUC score of 0.6521 on OTB2013. 
The differences will be solved in the future. (maybe, probable causes: im_crop? network forward? regularization? floating-point precision?)

Anyway, the **significance** of releasing this repository is to show **how to end-to-end train a CF tracker**.

You can easily modify this code into more modern methods (CCOT? CSRDCF? ECO?) and submit it to CVPR, ECCV...

Please give me a citation at that time!

**Comment by he010103** [comment]
@foolwood 
I get an AUC score of 65.75 on OTB2013 with your new parameters. Thanks for your help. I want to try some ideas in DCFNet.

**Comment by zhangxixi0904** [comment]
Hi! Could you please share the trained model ? I want to test some video now, but the dataset for training is quite large(86G).

**Comment by hwh3304** [comment]
@foolwood Hi there,
I can only get the AUC of 0.6338 with the parameters param.pth_scale_step_1.030_scale_penalty_0.990_interp_factor_0.012
Do any reasons result in this degradation? I run the code with window, Pycharm, Pytorch 0.4.0 and cuda 8.0.
Thank you.

**Comment by foolwood** [comment]
@hwh3304 
I have no idea. 
The system version (ubuntu or windows), the OpenCV version (can get different `imread` results), and even the GPU version (Pascal or Maxwell) all can affect performance.

**Comment by hwh3304** [comment]
@foolwood 
Thank you. I'll try on different setup.
