### ISSUE TITLE
代码疑问？

### ISSUE THREAD

**Issue by TerryYiDa** [foolwood/DCFNet_pytorch#2]
在tracking的DCFNet 中， 在求得 r_max, c_max后:
  if r_max > config.net_input_size[0] / 2:
                r_max = r_max - config.net_input_size[0]
            if c_max > config.net_input_size[1] / 2:
                c_max = c_max - config.net_input_size[1]

为什么要减去config.net_input_size[0]呢？

**Comment by foolwood** [comment]
@TerryYiDa 
这是因为，按照KCF在PAMI的论文中的方法，我们将高斯响应的中心移动至左上角。
当峰值响应在0-125/2之间的时候代表向右移动。当在125/2-125的时候是向左移动。

例如，峰值在124位置，其实就是（124-125）=-1向左移动1个pixel。
而如果在1位置，就是向右移动1个像素。
