### ISSUE TITLE
在python接口下测试的otb的AUC曲线图

### ISSUE THREAD

**Issue by yangkang779** [foolwood/DCFNet_pytorch#3]
https://github.com/bilylee/tracker_benchmark
作者好，请问如何用python在这个otb上画出测试DCFNet的曲线图呢？有没有run_DCF.py的测试脚本？谢谢。

**Comment by foolwood** [comment]
我不会去专门写这个接口。
代码非常简单，您可以自行修改。
而且我写的run_otb.py 已经可以得到AUC了，可视化出来并没什么额外的收益。
如果您喜欢可视化，我会在近期将我的所有可视化工具包分享出来。

**Comment by yangkang779** [comment]
好的，非常谢谢作者

**Comment by lupotto** [comment]
Hi @foolwood,

Any update in the visualization on DCF in this repo?
