### ISSUE TITLE
损失函数优化后大概损失值为多少

### ISSUE THREAD

**Issue by yangkang779** [foolwood/DCFNet_pytorch#6]
你好，我用你的网络直接训练的话的得到大概这样的损失：
Epoch: [49][8370/8399]  Time 0.482 (0.507)      Data 0.000 (0.001)      Loss 6.5989 (7.7805)
Epoch: [49][8380/8399]  Time 0.484 (0.507)      Data 0.000 (0.001)      Loss 7.5588 (7.7819)
Epoch: [49][8390/8399]  Time 0.478 (0.507)      Data 0.000 (0.001)      Loss 6.8010 (7.7822)
最后一个周期的，目前我还在测试的结果不是太好，改动了点，我后来又训练，一开始损失为Epoch: [0][8370/8399]   Time 0.394 (0.457)      Data 0.000 (0.001)      Loss 0.9896 (3.2535)
Epoch: [0][8380/8399]   Time 0.298 (0.457)      Data 0.000 (0.001)      Loss 1.0229 (3.2512)
Epoch: [0][8390/8399]   Time 0.381 (0.457)      Data 0.000 (0.001)      Loss 1.4456 (3.2489)
Test: [0/15]    Time 2.571 (2.571)      Loss 1.3802 (1.3802)

到20周期大概为

Epoch: [20][8370/8399]  Time 0.396 (0.418)      Data 0.000 (0.001)      Loss 0.1362 (0.1119)
Epoch: [20][8380/8399]  Time 0.340 (0.418)      Data 0.000 (0.001)      Loss 0.0682 (0.1119)
Epoch: [20][8390/8399]  Time 0.464 (0.418)      Data 0.000 (0.001)      Loss 0.1115 (0.1119)
Test: [0/15]    Time 2.563 (2.563)      Loss 0.0825 (0.0825)

我还没有跑完，这个损失相比有很大差别，请问这个损失值能衡量训练的好坏么？这个效果等训练结束我再测试。

**Comment by foolwood** [comment]
肯定是你的网络加了padding。

loss不可能这么小的。稳定了也在5左右。你这个0点几的是有问题的。

仔细看一下我训练时候的网络。
https://github.com/foolwood/DCFNet_pytorch/blob/17007f9cd8c0490f7d5f442bb1cc6aa466035b83/train/net.py#L17

训练的时候没有加padding，测试的时候加padding的。

**Comment by yangkang779** [comment]
对的，我训练的时候是加了padding=1的，因为我看到测试的时候加了，而训练的时候没加，之前看的网络大多是训练和测试是同样的padding大小的，大多数情况，所以我就想加个看看，会不会降低性能或者有什么区别。等训练完成再测试看看，这个地方加padding的话是训练错的么？dcfnet论文中卷积过后尺寸是没有变的，所以我就加了试试。

**Comment by yangkang779** [comment]
加了padding训练了25个周期之后损失很小但效果不好，这个不能填充。

**Comment by shnmng** [comment]
你好，我想请教下为什么不能加 padding ？

**Comment by Rheelt** [comment]
@yangkang779 你好，我想请问你用DCFNet_pytorch版本进行从头训练有复现作者的效果吗？我在50个epoch训练完了之后，loss下降到7.8左右，但是效果并不好。

**Comment by yangkang779** [comment]
效果多少呀？我能复现的啊，甚至有点高，把通道数改成96，就好了，别的不动，

**Comment by Rheelt** [comment]
@yangkang779 什么都没变，在OTB2013上训练出来是0.64，发现在单视频集上Bolt只有0.01这个是低于作者的单视频集上的Bolt的0.63。

**Comment by Rheelt** [comment]
@yangkang779 你好，可以将你训练好的pth文件（从头训练的和通道数为96），发给我吗？谢谢。邮箱：349249680@qq.com

**Comment by mydgs** [comment]
> @yangkang779 你好，我想请问你用DCFNet_pytorch版本进行从头训练有复现作者的效果吗？我在50个epoch训练完了之后，loss下降到7.8左右，但是效果并不好。
你好，我的也是下降到7.8左右，但是OTB2013只有0.48，请问你后来有发现问题所在吗
